### ISSUE TITLE
dotnet serve -d dist\demo1 not working in .NET 6

### ISSUE THREAD

**Issue by doggy8088** [natemcmaster/dotnet-serve#89] opened 2021-06-16 07:28 UTC
**Describe the bug**

The `-d` command option usage is not what I expected.

**To Reproduce**
1. Using this version (run `dotnet serve --version`): `1.8.34+6a96cbef9da7bfc86f6424f2ee499819cc617f7a`
2. Run these arguments '....'

    This command is not working.

    ```sh
    dotnet serve -d dist\demo1
    ```

    This is okay.

    ```sh
    dotnet serve --directory dist\demo1
    ```

    This is okay too.

    ```sh
    dotnet serve -d=dist\demo1
    ```

**Expected behavior**

    This command should working.

    ```sh
    dotnet serve -d dist\demo1
    ```

**Screenshots**

```log
Specify --help for a list of available options and commands.
Unexpected error: McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command or argument 'dist\demo1'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrParameter(CommandOrParameterArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at McMaster.DotNet.Serve.Program.Run(String[] args) in D:\a\dotnet-serve\dotnet-serve\src\dotnet-serve\Program.cs:line 46
```

![image](https://user-images.githubusercontent.com/88981/122176564-5710fc00-ceb7-11eb-9690-2b3b2460a26a.png)

**Additional context**

**Comment by natemcmaster** [comment] 2021-06-18 14:46
Weird. Doesn't reproduce on macOS with dotnet 5.0.101
![image](https://user-images.githubusercontent.com/2696087/122578741-09a4a400-d009-11eb-8c70-d75f370f3fbc.png)

@doggy8088 what does `dotnet --version` show? Also, does `dotnet-serve -d demo` work (dash instead of space between dotnet and serve)?

**Comment by doggy8088** [comment] 2021-06-18 14:50
@natemcmaster This might help. The .NET 6 is working.
![image](https://user-images.githubusercontent.com/88981/122579523-94c47f00-d087-11eb-829b-63c2037841f6.png)

**Comment by natemcmaster** [comment] 2021-06-18 15:00
Ok, so looks like .NET 6 CLI is eating up the `-d` parameter.

**Comment by natemcmaster** [comment] 2021-06-18 15:01
https://github.com/dotnet/sdk/issues/16120

**Comment by natemcmaster** [comment] 2021-06-18 15:06
@doggy8088 I'll need your help to make some noise to get the attention of the devs at Microsoft. This looks like a regression in .NET itself. I used to be one so know how many pings and issues they receive from github. 

In the meantime, try to workaround this by calling `dotnet-serve` instead of `dotnet serve`.

**Comment by doggy8088** [comment] 2021-06-18 15:26
This works to me too. 😅

```sh
dotnet serve -ddist\demo1
```

**Comment by natemcmaster** [comment] 2021-09-25 06:34
Closing as I this was an issue in .NET itself, not this tool. Thanks for the report!

**Closed by natemcmaster** 2021-09-25 06:34 UTC
Labels: bug, external

**Comment by mungojam** [comment] 2022-07-11 21:35
I've just hit this same issue using latest dotnet available on GitHub actions. How odd. I may not get time to dig into it to provide more info and not expecting you to re-open this or anything.
