### ISSUE TITLE
-a switch to set the address is not working

### ISSUE THREAD

**Issue by lejsekt** [natemcmaster/dotnet-serve#132] opened 2022-09-09 11:12 UTC
**Describe the bug**
The shorthand switch for "--address" - "-a" is not working.

**To Reproduce**
dotnet serve -a 0.0.0.0

Starting server, serving .
Listening on:
  http://localhost:35011

**Expected behavior**
I expect to be able reach the service on other interfaces than localhost, but only localhost works. Changing -a to --address fixes it.

Thank you.

**Comment by natemcmaster** [comment] 2022-09-11 03:04
Closing as a duplicate of #131

**Closed by natemcmaster** 2022-09-11 03:04 UTC
Labels: bug

**Comment by lejsekt** [comment] 2022-09-14 09:29
I see, the -a switch indeed works with an IP address such as 10.x.y.z.
