### ISSUE TITLE
[Question] Can I use this nuget package in C# project for .net 5 (not command line)

### ISSUE THREAD

**Issue by zydjohnHotmail** [natemcmaster/dotnet-serve#83] opened 2021-03-05 20:03 UTC
Hello:
I looked at your repo., it looks good.  But I need a small localhost http server in my C# project, my C# project will be running about 15 to 16 hours a day.
I can’t see any code example to run this in C# project (target .net 5.0)
Please show me some code example, if I can run a simple http server in C# project.
Thanks,

**Comment by natemcmaster** [comment] 2021-03-07 17:54
This looks like a duplicate of https://github.com/natemcmaster/dotnet-serve/issues/39.

I don't plan to support using the code as a class library, but if someone wants to go to the trouble of refactoring the code to support it, I would consider accepting a pull request.

**Closed by natemcmaster** 2021-03-07 17:54 UTC
Labels: question
